# config.yaml
comet:
  api_key: "Kneh4rDqtRHtLmTN6AvhSShWA"
  project_name: "deepcube"
  workspace: "lytofb"
data:
  num_samples: 10000
  min_scramble: 8
  max_scramble: 25
  batch_size: 128

diffusion:
  schedule_start: 0.1
  schedule_end: 0.7
  num_steps: 10

model:
  cond_dim: 54
  d_model: 128
  n_layers: 4
  n_heads: 4
  p_drop: 0.1
  max_seq_len: 50

training:
  epochs: 5
  learning_rate: 1e-4